<!DOCTYPE html>

<!-- include RHAS -->
<script src="js/rhas/map/housemap.js"></script>
<script src="js/rhas/control.js"></script>

<script>
var control;
</script>

<div class="row centercontent highlightrow">
  <img id="mapimage_orig" class="mapimage" src="js/rhas/map/map.png" onload="if (navigator.userAgent.match(/AppleWebKit/)) {imageLoaded();}" style="display: none;"/>
  <img id="mapimage" class="mapimage" src="js/rhas/map/map.png"/>
</div>

<div class="body-content">
  <div id="alertzone"></div>
  <div id="switches" class="row" style="display: none;">
    <h4>Switches</h4>
    <div class="col-lg-4" id="switchlist1">

    </div>
    <div class="col-lg-4" id="switchlist2">

    </div>
    <div class="col-lg-4" id="switchlist3">

    </div>
  </div>
</div>

<script>
//TODO: Used quite an idiotic construction to make it work in Safari and Firefox. Check the onload event on img, that's needed for safari because it should wait until the 
  // image loaded before executing the javascript. Strange fact is that that solution triggers an "function not found" for imageLoaded() on Firefox. So, both solutions added. Quite
  // dirty
  
  function startPage() {
    if (!navigator.userAgent.match(/AppleWebKit/)) {
      control = new ControlPage(document.getElementById('mapimage_orig'), document.getElementById("mapimage"));
      control.start();
    }
    
    //Check level and enable certain functionality
    doApiCall("common", "GetClearanceLevel", {}, false, function(data) {
      if (data.level >= 5) {
        $("#switches").show();
      }
    });
  }
  
  function stopPage() {
    control = undefined;
  }
  
  function imageLoaded() {
     control = new ControlPage(document.getElementById('mapimage_orig'), document.getElementById("mapimage"));
     control.start();
  }
</script>