<!DOCTYPE html>
<script src="js/rhas/control.js"></script>
<script>
var control;
</script>

<h4>Switches</h4>
<div id="alertzone"></div>
<div class="row-fluid switches">
  <div class="span4" id="switchlist1">

  </div>
  <div class="span4" id="switchlist2">

  </div>
  <div class="span4" id="switchlist3">

  </div>
</div>

<script>
  function startPage() {
    control = new ControlPage();
    control.start();
  }
  
  function stopPage() {
  
  }
</script>