<!DOCTYPE html>

<div class="body-content">
  <div class="row">
    <h4>Ruud's Home Automation System</h4>
    <div class="col-lg-10">
      Ruud's Home Automation System is started as a hobby project to play around with some domotica hardware I got and my recently buyed Raspberry PI. Maybe it will end up as a full blown home automation system, especially for myself. (Hurray!)<br/>
     &nbsp;<br/>
      At this moment it has the following features:<br/>
      &nbsp;<br/>
      <ul>
        <li>Written in PHP with Mysql, and at the clientside a lot of modern (hopefully) Javascript, HTML5 and CSS!</li>
        <li>A nicely designed (IMHO) and extensible API (with authorisation support.</li>
        &nbsp;<br/>
        <li>Gather sensor data from my <a href="http://www.homewizard.nl" target="_blank">Homewizard</a> and put in a MySql database for further reference.</li>
        <li>Get temperature data and generate nice <a href="http://www.jqplot.com" target="_blank">jqPlot</a> graphs with it.</li>
        <li>Get temperature data and plot them in a map of my house (with nice colors!).</li>
        &nbsp;<br/>
        <li>Shows some quick weather info from dutch sites.</li>
      </ul>
    </div>
    <div class="col-lg-2">
      <img src="img/ico/apple-touch-icon-144-precomposed.png"/>
    </div>

  </div>

  <hr>
  
  <div class="row">
    <h4>Opensource on GitHub!</h4>
    <div class="col-lg-8">
      RHAS (Ruud's Home Automation System) is, how unexpected, developed by <a href="http://www.ruudgreven.nl" target="_blank">someone named Ruud</a>. You are free to download the source and modify it to your own needs.<br/>
      &nbsp;<br/>
      Check out the <a href="https://github.com/ruudgreven/RHAS" target="_blank">GitHub repo</a>
    </div>
    <div class="col-lg-4">
      <a href="https://github.com/ruudgreven/RHAS" target="_blank"><img src="img/github_octocat.png"/></a>
    </div>
  </div>
</div>

<script>
  function startPage() {

  }
  
  function stopPage() {
  
  }
</script>