<!DOCTYPE html>
<script src="js/rhas/settings.js"></script>

<h4>Login for API</h4>

<div class="row-fluid">
  <div id="alertzone"></div>
  <form>
    Username: <input type="text" id="username"/><br/>
    Private key: <input type="text" id="privatekey"/><br/>
  </form>
  <button onClick="saveLoginForAPI($('#username').val(), $('#privatekey').val());">Opslaan</button>&nbsp;
  <button onClick="clearCredentials();">Clear current credentials</button><br/>
  &nbsp;<br/>
</div>

<h4>Check clearance level</h4>
Your active clearance level is <strong id="clearancelevel">#</strong>. &nbsp;<button onClick="getClearanceLevel();">Check!</button><br/>
&nbsp;
<script>
  startSettings();
</script>