<!DOCTYPE html>
<script src="js/rhas/settings.js"></script>
<script>
var settings;
</script>

<div class="body-content">
  <h4>Login for API</h4>

  <div class="row">
    <div id="alertzone"></div>
    <form>
      Username: <input type="text" id="username"/><br/>
      Private key: <input type="text" id="privatekey"/><br/>
    </form>
    <button onClick="settings.saveLoginForAPI($('#username').val(), $('#privatekey').val());">Opslaan</button>&nbsp;
    <button onClick="settings.clearCredentials();">Clear current credentials</button><br/>
    &nbsp;<br/>
  </div>

  <h4>Check clearance level</h4>
  Your active clearance level is <strong id="clearancelevel">#</strong>. &nbsp;<button onClick="settings.getClearanceLevel();">Check!</button><br/>
  &nbsp;
</div>

<script>
  function startPage() {
    settings = new SettingsPage();
    settings.start();
  }
  
  function stopPage() {
  
  }
</script>