<!DOCTYPE html>
<script src="js/rhas/settings.js"></script>

<h4>Login voor API</h4>
<div id="alert_failed" class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Warning!</strong> User seems not valid.
</div>

<div id="alert_ok" class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  Users seems ok. Settings saved!
</div>

<div class="row-fluid">
  <form>
    Username: <input type="text" id="username"/><br/>
    Private key: <input type="text" id="privatekey"/><br/>
  </form>
  <button onClick="saveLoginForAPI($('#username').val(), $('#privatekey').val());">Opslaan</button><br/>
  &nbsp;<br/>
</div>

<script>
  startSettings();
</script>