<!DOCTYPE html>

<!-- Include jqPlot -->
<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="lib/jqplot/excanvas.js"></script><![endif]-->
<script language="javascript" type="text/javascript" src="lib/jqplot/jquery.jqplot.min.js"></script>
<script language="javascript" type="text/javascript" src="lib/jqplot/plugins/jqplot.cursor.min.js"></script>
<script language="javascript" type="text/javascript" src="lib/jqplot/plugins/jqplot.highlighter.min.js"></script>
<script language="javascript" type="text/javascript" src="lib/jqplot/plugins/jqplot.dateAxisRenderer.min.js"></script>
<link rel="stylesheet" type="text/css" href="lib/jqplot/jquery.jqplot.css" />

<!-- include RHAS -->
<script src="js/rhas/map/housemap.js"></script>
<script src="js/rhas/temperature.js"></script>


<div class="map">
  <img id="mapimage_orig" src="js/rhas/map/map.png" style="display: none;"/>
  <img id="mapimage" src="js/rhas/map/map.png"/>
</div>

<hr>

<div class="row-fluid sensors">
  <div class="span6" id="sensorlist1">

  </div>

  <div class="span6" id="sensorlist2">
  
  </div>
</div>

	
<script>
  var temperature = new TemperaturePage(document.getElementById('mapimage_orig'), document.getElementById("mapimage"));
  temperature.start();
</script>