<!DOCTYPE html>

<!-- Include jqPlot -->
<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="lib/jqplot/excanvas.js"></script><![endif]-->
<script language="javascript" type="text/javascript" src="lib/jqplot/jquery.jqplot.min.js"></script>
<script language="javascript" type="text/javascript" src="lib/jqplot/plugins/jqplot.cursor.min.js"></script>
<script language="javascript" type="text/javascript" src="lib/jqplot/plugins/jqplot.highlighter.min.js"></script>
<script language="javascript" type="text/javascript" src="lib/jqplot/plugins/jqplot.dateAxisRenderer.min.js"></script>
<link rel="stylesheet" type="text/css" href="lib/jqplot/jquery.jqplot.css" />

<!-- include RHAS -->
<script src="js/rhas/map/housemap.js"></script>
<script src="js/rhas/temperature.js"></script>
<script>
var temperature;
</script>

<div class="map">
  <img id="mapimage_orig" src="js/rhas/map/map.png" onload="if (navigator.userAgent.match(/AppleWebKit/)) {imageLoaded();}" style="display: none;"/>
  <img id="mapimage" src="js/rhas/map/map.png"/>
</div>

<hr>

<div class="row-fluid sensors">
  <div class="span6" id="sensorlist1">

  </div>

  <div class="span6" id="sensorlist2">
  
  </div>
</div>

	
<script>
  //TODO: Used quite an idiotic construction to make it work in Safari and Firefox. Check the onload event on img, that's needed for safari because it should wait until the 
  // image loaded before executing the javascript. Strange fact is that that solution triggers an "function not found" for imageLoaded() on Firefox. So, both solutions added. Quite
  // dirty
  
  function startPage() {
    if (!navigator.userAgent.match(/AppleWebKit/)) {
      temperature = new TemperaturePage(document.getElementById('mapimage_orig'), document.getElementById("mapimage"));
      temperature.start();
    }
  }
  
  function stopPage() {
    temperature = undefined;
  }
  
  function imageLoaded() {
     temperature = new TemperaturePage(document.getElementById('mapimage_orig'), document.getElementById("mapimage"));
     temperature.start();
  }
</script>