<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>RHAS</title>

		<link href="css/rhas.css" rel="stylesheet">
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
    
    <script src="js/jquery-1.10.2.min.js"></script>
    <script src="js/bootstrap-min.js"></script>
    
    <script>
     $(document).ready(function() {
      //Report to parent that were done!
      parent.loadingDone(document.body.scrollHeight)
    });
    </script>
  </head>

  <body>
    <div class="container-narrow">
			<hr>
      <h4>Buienradar</h4>
      <div class="row-fluid">
    		<div class="span6">
        	<a href="http://www.buienradar.nl" target="_new"><img src="http://traffic-583416025.eu-west-1.elb.amazonaws.com/v2/images.aspx" alt="Buienradar NL"/></a>
        </div>
        <div class="span6">
        	<a href="http://www.meteox.nl" target="_new"><img src="http://europa.buienradar.nl/images.aspx?jaar=-3&voor=&soort=loop1uur" alt="Buienrader EU"/></a>
        </div>
      </div>
      
      <hr>
			<h4>KNMI</h4>
      <div class="row-fluid">
      	<div class="span8">
      		<img src="http://www.knmi.nl/actueel/images/tempgmt.png"/>
      	</div>
        <div class="span4">
        	<a href="http://www.knmi.nl/" target="_new"><img src="http://www.knmi.nl/waarschuwingen_en_verwachtingen/images/knmi_web_weersverwachting.png" alt="weersverwachting" title="weersverwachting" border="0" width="220"></a>
        	&nbsp;&nbsp;
        	<div style="width: 220; height: 272">
						<a href="http://www.knmi.nl/" target="_new"><img src="http://www.knmi.nl/waarschuwingen_en_verwachtingen/images/weeralarm_info.gif"  alt="Waarschuwing voor Extreem weer of Weeralarm!" title="Waarschuwing voor Extreem weer of Weeralarm!" border="0" width="220"></a>
					</div>
        </div>
      </div>
    </div> <!-- /container -->
  </body>
</html>
